// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlU_SxsQxofgYcaH937bRYmkj5dvRhLnU',
    appId: '1:909172288991:web:edd3f100d11db65d44a86a',
    messagingSenderId: '909172288991',
    projectId: 'fir-app-13843',
    authDomain: 'fir-app-13843.firebaseapp.com',
    storageBucket: 'fir-app-13843.appspot.com',
    measurementId: 'G-F3Z694KCKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs_Pe-BQm_vcysxgMBcZH9ZKLiapc0ScI',
    appId: '1:909172288991:android:b7102ddcb44e193444a86a',
    messagingSenderId: '909172288991',
    projectId: 'fir-app-13843',
    storageBucket: 'fir-app-13843.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAR31vK4ze4q1DqQF0eQen3hZjVJEkhb0',
    appId: '1:909172288991:ios:c9ca9af2dd13c14544a86a',
    messagingSenderId: '909172288991',
    projectId: 'fir-app-13843',
    storageBucket: 'fir-app-13843.appspot.com',
    iosClientId: '909172288991-f6pq40b45le5t4mvcr4483kjj87priqt.apps.googleusercontent.com',
    iosBundleId: 'com.example.earthHaven',
  );

}