// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlU_SxsQxofgYcaH937bRYmkj5dvRhLnU',
    appId: '1:909172288991:web:82da81fc559128a744a86a',
    messagingSenderId: '909172288991',
    projectId: 'fir-app-13843',
    authDomain: 'fir-app-13843.firebaseapp.com',
    storageBucket: 'fir-app-13843.appspot.com',
    measurementId: 'G-Q6GK63JYCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs_Pe-BQm_vcysxgMBcZH9ZKLiapc0ScI',
    appId: '1:909172288991:android:9d0f0f42b6b5143244a86a',
    messagingSenderId: '909172288991',
    projectId: 'fir-app-13843',
    storageBucket: 'fir-app-13843.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAR31vK4ze4q1DqQF0eQen3hZjVJEkhb0',
    appId: '1:909172288991:ios:604c32b82eefe12a44a86a',
    messagingSenderId: '909172288991',
    projectId: 'fir-app-13843',
    storageBucket: 'fir-app-13843.appspot.com',
    iosClientId: '909172288991-vqvdkurk1ajm3vcft3sjffhgrtgl6l50.apps.googleusercontent.com',
    iosBundleId: 'com.example.xfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAR31vK4ze4q1DqQF0eQen3hZjVJEkhb0',
    appId: '1:909172288991:ios:bb39d1467e36a76c44a86a',
    messagingSenderId: '909172288991',
    projectId: 'fir-app-13843',
    storageBucket: 'fir-app-13843.appspot.com',
    iosClientId: '909172288991-3aqpau9129qmf2ekuv3a5gnj4l46c4mq.apps.googleusercontent.com',
    iosBundleId: 'com.example.xfirebase.RunnerTests',
  );
}
